 #Faça um programa que solicite ao usuário 2 valores, utilize uma condição ternária para escrever qual o maior valor: 
  #o primeiro ou o segundo (caso os valores sejam iguais, considere o segundo).

  print(f"O maior valor é: {max(float(input('Digite o primeiro valor: ')), float(input('Digite o segundo valor: ')))}")

#Faça um programa que solicite o nome do usuário e depois disso faça uma saudação no formato: "Olá {nome digitado pelo usuário}".

nome = input("digite o seu nome: ")

print(f"ola {nome}")