
#Faça um algoritmo que solicite o nome do usuário e depois escreva o nome da pessoa no console.

nome = input("qual seu e seu nome")


print("ola," + nome +  "!")

#Faça um algoritmo que pergunte ao usuário quantos anos ele tem, depois disso, escreva True no console,
  #caso ele já tenha alcançado a maioridade (18 anos), caso contrário escreva False.

idade = int(input("Quantos anos você tem? "))


if idade >= 18:
      print(True)
else:
 print(False)







    

#
 
 
